# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: oracle-mysql:8.0
    disk: 1024

searchelastic:
    type: elasticsearch:7.7
    disk: 2048

queuerabbit:
    type: rabbitmq:3.8
    disk: 2048

#search:
#    type: elasticsearch:7.7
#    disk: 2048
#    configuration:
#        authentication:
#            enabled: true





